import { Injectable } from '@angular/core';

import { BillingQueue } from '../@entities/billing-queue';
import { Category } from '../@entities/category';
import { Product } from '../@entities/product';
import { Table } from '../@entities/table';

@Injectable({
  providedIn: 'root',
})
export class DummyService {
  public tableData: Table[] = [
    {
      table: 'T-01',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-02',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-03',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-04',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-05',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-06',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-07',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-08',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-09',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-10',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-11',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-12',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-13',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-14',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-15',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-16',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-17',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-18',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-19',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-20',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-21',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-22',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-23',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-24',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-25',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-26',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-27',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-28',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-29',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-30',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-31',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-32',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-33',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-34',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-35',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-36',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-37',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-38',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-39',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 2,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-40',
      customerCount: 0,
      customerName: '',
      maxCustomerCount: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
  ];

  public categoryList: Category[] = [
    {
      id: 1,
      name: 'all menu',
      slug: 'all-menu',
      icon: 'icons/book-open.svg',
    },
    {
      id: 2,
      name: 'breads',
      slug: 'breads',
      icon: 'icons/cookie.svg',
    },
    {
      id: 3,
      name: 'cakes',
      slug: 'cakes',
      icon: 'icons/cake.svg',
    },
    {
      id: 4,
      name: 'donuts',
      slug: 'donuts',
      icon: 'icons/donut.svg',
    },
    {
      id: 5,
      name: 'pastries',
      slug: 'pastries',
      icon: 'icons/croissant.svg',
    },
    {
      id: 6,
      name: 'sandwich',
      slug: 'sandwich',
      icon: 'icons/sandwich.svg',
    },
    {
      id: 6,
      name: 'coffee',
      slug: 'coffee',
      icon: 'icons/coffee.svg',
    },
    {
      id: 6,
      name: 'non coffee',
      slug: 'non-coffee',
      icon: 'icons/cup-soda.svg',
    },
  ];

  public productList: Product[] = [
    // Breads
    {
      id: 1,
      name: 'French Baguette',
      category: 'breads',
      amount: 0,
      price: 25000,
      description: 'Crispy on the outside, soft on the inside.',
      note: '',
    },
    {
      id: 2,
      name: 'Whole Wheat Bread',
      category: 'breads',
      amount: 0,
      price: 20000,
      description: 'Healthy bread made from 100% whole wheat.',
      note: '',
    },
    {
      id: 3,
      name: 'Sourdough Loaf',
      category: 'breads',
      amount: 0,
      price: 30000,
      description: 'Tangy flavor with a chewy crust.',
      note: '',
    },
    {
      id: 4,
      name: 'Ciabatta',
      category: 'breads',
      amount: 0,
      price: 28000,
      description: 'Italian bread with a light texture.',
      note: '',
    },
    {
      id: 5,
      name: 'Brioche Bun',
      category: 'breads',
      amount: 0,
      price: 22000,
      description: 'Soft and buttery French bread.',
      note: '',
    },
    {
      id: 6,
      name: 'Bagel',
      category: 'breads',
      amount: 0,
      price: 18000,
      description: 'Chewy bread with a dense texture.',
      note: '',
    },
    {
      id: 7,
      name: 'Pita Bread',
      category: 'breads',
      amount: 0,
      price: 15000,
      description: 'Soft and thin Middle Eastern flatbread.',
      note: '',
    },
    {
      id: 8,
      name: 'Rye Bread',
      category: 'breads',
      amount: 0,
      price: 25000,
      description: 'Dense bread with a slightly sour flavor.',
      note: '',
    },
    {
      id: 9,
      name: 'Focaccia',
      category: 'breads',
      amount: 0,
      price: 28000,
      description: 'Flat Italian bread seasoned with olive oil and herbs.',
      note: '',
    },
    {
      id: 10,
      name: 'Challah',
      category: 'breads',
      amount: 0,
      price: 30000,
      description: 'Sweet, braided bread for special occasions.',
      note: '',
    },

    // Cakes
    {
      id: 11,
      name: 'Chocolate Cake',
      category: 'cakes',
      amount: 0,
      price: 40000,
      description: 'Rich and moist chocolate layered cake.',
      note: '',
    },
    {
      id: 12,
      name: 'Vanilla Sponge Cake',
      category: 'cakes',
      amount: 0,
      price: 35000,
      description: 'Light and fluffy cake with vanilla flavor.',
      note: '',
    },
    {
      id: 13,
      name: 'Cheesecake',
      category: 'cakes',
      amount: 0,
      price: 45000,
      description: 'Creamy and smooth, topped with fresh fruits.',
      note: '',
    },
    {
      id: 14,
      name: 'Red Velvet Cake',
      category: 'cakes',
      amount: 0,
      price: 42000,
      description: 'Velvety soft cake with a hint of cocoa.',
      note: '',
    },
    {
      id: 15,
      name: 'Carrot Cake',
      category: 'cakes',
      amount: 0,
      price: 40000,
      description: 'Moist cake with carrots and cream cheese frosting.',
      note: '',
    },
    {
      id: 16,
      name: 'Black Forest Cake',
      category: 'cakes',
      amount: 0,
      price: 45000,
      description: 'Layers of chocolate cake with cherries and cream.',
      note: '',
    },
    {
      id: 17,
      name: 'Opera Cake',
      category: 'cakes',
      amount: 0,
      price: 50000,
      description: 'Elegant French layered cake with coffee and chocolate.',
      note: '',
    },
    {
      id: 18,
      name: 'Lemon Drizzle Cake',
      category: 'cakes',
      amount: 0,
      price: 37000,
      description: 'Zesty lemon-flavored sponge cake.',
      note: '',
    },
    {
      id: 19,
      name: 'Tiramisu',
      category: 'cakes',
      amount: 0,
      price: 48000,
      description: 'Classic Italian dessert with coffee and mascarpone.',
      note: '',
    },
    {
      id: 20,
      name: 'Fruit Cake',
      category: 'cakes',
      amount: 0,
      price: 40000,
      description: 'Dense cake with dried fruits and nuts.',
      note: '',
    },

    // Donuts
    {
      id: 21,
      name: 'Glazed Donut',
      category: 'donuts',
      amount: 0,
      price: 12000,
      description: 'Classic donut with a sweet glaze.',
      note: '',
    },
    {
      id: 22,
      name: 'Chocolate Donut',
      category: 'donuts',
      amount: 0,
      price: 15000,
      description: 'Donut coated with rich chocolate.',
      note: '',
    },
    {
      id: 23,
      name: 'Sugar Donut',
      category: 'donuts',
      amount: 0,
      price: 10000,
      description: 'Soft donut rolled in sugar.',
      note: '',
    },
    {
      id: 24,
      name: 'Boston Cream Donut',
      category: 'donuts',
      amount: 0,
      price: 18000,
      description: 'Filled with vanilla custard and topped with chocolate.',
      note: '',
    },
    {
      id: 25,
      name: 'Jelly Donut',
      category: 'donuts',
      amount: 0,
      price: 16000,
      description: 'Donut filled with fruity jelly.',
      note: '',
    },
    {
      id: 26,
      name: 'Cinnamon Twist',
      category: 'donuts',
      amount: 0,
      price: 14000,
      description: 'Twisted donut with a cinnamon sugar coating.',
      note: '',
    },
    {
      id: 27,
      name: 'Maple Donut',
      category: 'donuts',
      amount: 0,
      price: 17000,
      description: 'Topped with sweet maple glaze.',
      note: '',
    },
    {
      id: 28,
      name: 'Powdered Sugar Donut',
      category: 'donuts',
      amount: 0,
      price: 11000,
      description: 'Donut dusted with powdered sugar.',
      note: '',
    },
    {
      id: 29,
      name: 'Old-Fashioned Donut',
      category: 'donuts',
      amount: 0,
      price: 15000,
      description: 'Traditional cake-style donut.',
      note: '',
    },
    {
      id: 30,
      name: 'Cruller',
      category: 'donuts',
      amount: 0,
      price: 16000,
      description: 'Light and airy, with a sweet glaze.',
      note: '',
    },

    // Pastries
    {
      id: 31,
      name: 'Croissant',
      category: 'pastries',
      amount: 0,
      price: 25000,
      description: 'Buttery and flaky French pastry.',
      note: '',
    },
    {
      id: 32,
      name: 'Pain au Chocolat',
      category: 'pastries',
      amount: 0,
      price: 28000,
      description: 'Croissant filled with rich chocolate.',
      note: '',
    },
    {
      id: 33,
      name: 'Danish Pastry',
      category: 'pastries',
      amount: 0,
      price: 30000,
      description: 'Flaky pastry filled with cream or fruit.',
      note: '',
    },
    {
      id: 34,
      name: 'Apple Turnover',
      category: 'pastries',
      amount: 0,
      price: 32000,
      description: 'Pastry filled with spiced apple filling.',
      note: '',
    },
    {
      id: 35,
      name: 'Éclair',
      category: 'pastries',
      amount: 0,
      price: 35000,
      description: 'Choux pastry filled with cream and topped with chocolate.',
      note: '',
    },
    {
      id: 36,
      name: 'Palmier',
      category: 'pastries',
      amount: 0,
      price: 20000,
      description: 'Crispy and caramelized puff pastry.',
      note: '',
    },
    {
      id: 37,
      name: 'Strudel',
      category: 'pastries',
      amount: 0,
      price: 33000,
      description: 'Layered pastry with fruit or nut filling.',
      note: '',
    },
    {
      id: 38,
      name: 'Madeleine',
      category: 'pastries',
      amount: 0,
      price: 18000,
      description: 'Soft shell-shaped sponge cakes.',
      note: '',
    },
    {
      id: 39,
      name: 'Profiterole',
      category: 'pastries',
      amount: 0,
      price: 36000,
      description: 'Choux pastry filled with cream and topped with chocolate.',
      note: '',
    },
    {
      id: 40,
      name: 'Cannelé',
      category: 'pastries',
      amount: 0,
      price: 26000,
      description:
        'Small French pastry with a caramelized crust and soft inside.',
      note: '',
    },

    // Sandwiches
    {
      id: 41,
      name: 'Club Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 40000,
      description: 'Triple-layered sandwich with chicken, bacon, and lettuce.',
      note: '',
    },
    {
      id: 42,
      name: 'BLT Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 35000,
      description: 'Classic bacon, lettuce, and tomato sandwich.',
      note: '',
    },
    {
      id: 43,
      name: 'Egg Salad Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 30000,
      description: 'Creamy egg salad on toasted bread.',
      note: '',
    },
    {
      id: 44,
      name: 'Tuna Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 32000,
      description: 'Fresh tuna salad with lettuce and tomato.',
      note: '',
    },
    {
      id: 45,
      name: 'Grilled Cheese',
      category: 'sandwich',
      amount: 0,
      price: 28000,
      description: 'Melted cheese between crispy toasted bread.',
      note: '',
    },
    {
      id: 46,
      name: 'Reuben Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 45000,
      description: 'Corned beef, sauerkraut, Swiss cheese, and rye bread.',
      note: '',
    },
    {
      id: 47,
      name: 'Turkey Club',
      category: 'sandwich',
      amount: 0,
      price: 40000,
      description: 'Layers of turkey, bacon, lettuce, and tomato.',
      note: '',
    },
    {
      id: 48,
      name: 'Veggie Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 35000,
      description: 'Loaded with fresh vegetables and avocado.',
      note: '',
    },
    {
      id: 49,
      name: 'Ham and Cheese',
      category: 'sandwich',
      amount: 0,
      price: 30000,
      description: 'Classic ham and melted cheese sandwich.',
      note: '',
    },
    {
      id: 50,
      name: 'Pastrami Sandwich',
      category: 'sandwich',
      amount: 0,
      price: 45000,
      description: 'Savory pastrami with mustard on rye bread.',
      note: '',
    },

    // Coffee
    {
      id: 51,
      name: 'Espresso',
      category: 'coffee',
      amount: 0,
      price: 25000,
      description: 'Strong and concentrated coffee shot.',
      note: '',
    },
    {
      id: 52,
      name: 'Americano',
      category: 'coffee',
      amount: 0,
      price: 25000,
      description: 'Espresso diluted with hot water.',
      note: '',
    },
    {
      id: 53,
      name: 'Cappuccino',
      category: 'coffee',
      amount: 0,
      price: 30000,
      description: 'Espresso with steamed milk and foam.',
      note: '',
    },
    {
      id: 54,
      name: 'Latte',
      category: 'coffee',
      amount: 0,
      price: 35000,
      description: 'Espresso with steamed milk.',
      note: '',
    },
    {
      id: 55,
      name: 'Flat White',
      category: 'coffee',
      amount: 0,
      price: 30000,
      description: 'Silky espresso-based coffee with microfoam.',
      note: '',
    },
    {
      id: 56,
      name: 'Mocha',
      category: 'coffee',
      amount: 0,
      price: 40000,
      description: 'Espresso mixed with chocolate and steamed milk.',
      note: '',
    },
    {
      id: 57,
      name: 'Macchiato',
      category: 'coffee',
      amount: 0,
      price: 28000,
      description: 'Espresso topped with a dollop of foam.',
      note: '',
    },
    {
      id: 58,
      name: 'Affogato',
      category: 'coffee',
      amount: 0,
      price: 45000,
      description: 'Espresso poured over vanilla ice cream.',
      note: '',
    },
    {
      id: 59,
      name: 'Cold Brew',
      category: 'coffee',
      amount: 0,
      price: 35000,
      description: 'Slow-steeped coffee served cold.',
      note: '',
    },
    {
      id: 60,
      name: 'Iced Latte',
      category: 'coffee',
      amount: 0,
      price: 37000,
      description: 'Cold espresso with milk and ice.',
      note: '',
    },

    // Non-Coffee
    {
      id: 61,
      name: 'Hot Chocolate',
      category: 'non-coffee',
      amount: 0,
      price: 30000,
      description: 'Rich chocolate drink topped with whipped cream.',
      note: '',
    },
    {
      id: 62,
      name: 'Chai Latte',
      category: 'non-coffee',
      amount: 0,
      price: 35000,
      description: 'Spiced tea blended with steamed milk.',
      note: '',
    },
    {
      id: 63,
      name: 'Matcha Latte',
      category: 'non-coffee',
      amount: 0,
      price: 40000,
      description: 'Green tea powder with milk.',
      note: '',
    },
    {
      id: 64,
      name: 'Iced Tea',
      category: 'non-coffee',
      amount: 0,
      price: 25000,
      description: 'Refreshing cold brewed tea.',
      note: '',
    },
    {
      id: 65,
      name: 'Lemonade',
      category: 'non-coffee',
      amount: 0,
      price: 25000,
      description: 'Sweet and tangy lemon drink.',
      note: '',
    },
    {
      id: 66,
      name: 'Milkshake',
      category: 'non-coffee',
      amount: 0,
      price: 40000,
      description: 'Blended milk and ice cream in various flavors.',
      note: '',
    },
    {
      id: 67,
      name: 'Smoothie',
      category: 'non-coffee',
      amount: 0,
      price: 42000,
      description: 'Blended fresh fruits with yogurt or milk.',
      note: '',
    },
    {
      id: 68,
      name: 'Herbal Tea',
      category: 'non-coffee',
      amount: 0,
      price: 30000,
      description: 'Caffeine-free tea made from herbs and flowers.',
      note: '',
    },
    {
      id: 69,
      name: 'Sparkling Water',
      category: 'non-coffee',
      amount: 0,
      price: 20000,
      description: 'Lightly carbonated water.',
      note: '',
    },
    {
      id: 70,
      name: 'Juice',
      category: 'non-coffee',
      amount: 0,
      price: 35000,
      description: 'Freshly squeezed fruit juice.',
      note: '',
    },
  ];

  public billingQueueList: BillingQueue[] = [
    {
      id: 1,
      name: 'David',
      orderNumber: '#001',
      table: '34',
      totalPayment: 955868,
      status: true,
      createdAt: '2025-01-15 10:57:00 AM',
    },
    {
      id: 2,
      name: 'Tom',
      orderNumber: '#002',
      table: '40',
      totalPayment: 328818,
      status: false,
      createdAt: '2025-01-15 02:27:00 PM',
    },
    {
      id: 3,
      name: 'Jack',
      orderNumber: '#003',
      table: '37',
      totalPayment: 791627,
      status: false,
      createdAt: '2025-01-15 02:12:00 PM',
    },
    {
      id: 4,
      name: 'George',
      orderNumber: '#004',
      table: '34',
      totalPayment: 383140,
      status: true,
      createdAt: '2025-01-15 06:53:00 PM',
    },
    {
      id: 5,
      name: 'Liam',
      orderNumber: '#005',
      table: '22',
      totalPayment: 579615,
      status: false,
      createdAt: '2025-01-15 05:18:00 PM',
    },
    {
      id: 6,
      name: 'Liam',
      orderNumber: '#006',
      table: '09',
      totalPayment: 413587,
      status: true,
      createdAt: '2025-01-15 11:27:00 AM',
    },
    {
      id: 7,
      name: 'David',
      orderNumber: '#007',
      table: '26',
      totalPayment: 201221,
      status: false,
      createdAt: '2025-01-15 12:30:00 PM',
    },
    {
      id: 8,
      name: 'Paul',
      orderNumber: '#008',
      table: '25',
      totalPayment: 214922,
      status: true,
      createdAt: '2025-01-15 10:43:00 AM',
    },
    {
      id: 9,
      name: 'Paul',
      orderNumber: '#009',
      table: '29',
      totalPayment: 680573,
      status: false,
      createdAt: '2025-01-15 09:07:00 PM',
    },
    {
      id: 10,
      name: 'Quincy',
      orderNumber: '#010',
      table: '04',
      totalPayment: 489592,
      status: false,
      createdAt: '2025-01-15 09:16:00 PM',
    },
    {
      id: 11,
      name: 'Alice',
      orderNumber: '#011',
      table: '29',
      totalPayment: 759653,
      status: true,
      createdAt: '2025-01-15 04:02:00 PM',
    },
    {
      id: 12,
      name: 'Paul',
      orderNumber: '#012',
      table: '21',
      totalPayment: 700062,
      status: false,
      createdAt: '2025-01-15 02:04:00 PM',
    },
    {
      id: 13,
      name: 'Paul',
      orderNumber: '#013',
      table: '31',
      totalPayment: 630593,
      status: true,
      createdAt: '2025-01-15 07:23:00 PM',
    },
    {
      id: 14,
      name: 'Noah',
      orderNumber: '#014',
      table: '16',
      totalPayment: 536026,
      status: true,
      createdAt: '2025-01-15 11:50:00 AM',
    },
    {
      id: 15,
      name: 'Sophia',
      orderNumber: '#015',
      table: '40',
      totalPayment: 486709,
      status: false,
      createdAt: '2025-01-15 10:52:00 AM',
    },
    {
      id: 16,
      name: 'Jack',
      orderNumber: '#016',
      table: '03',
      totalPayment: 291768,
      status: false,
      createdAt: '2025-01-15 09:51:00 PM',
    },
    {
      id: 17,
      name: 'Fiona',
      orderNumber: '#017',
      table: '04',
      totalPayment: 864085,
      status: true,
      createdAt: '2025-01-15 06:36:00 PM',
    },
    {
      id: 18,
      name: 'Sophia',
      orderNumber: '#018',
      table: '13',
      totalPayment: 918687,
      status: true,
      createdAt: '2025-01-15 05:43:00 PM',
    },
    {
      id: 19,
      name: 'David',
      orderNumber: '#019',
      table: '04',
      totalPayment: 769709,
      status: false,
      createdAt: '2025-01-15 12:47:00 PM',
    },
    {
      id: 20,
      name: 'Tom',
      orderNumber: '#020',
      table: '03',
      totalPayment: 860153,
      status: true,
      createdAt: '2025-01-15 11:27:00 AM',
    },
  ];

  constructor() {}
}
