import { Table } from './../@entities/table';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DummyService {
  public tableData: Table[] = [
    {
      table: 'T-01',
      personAmount: 2,
      personName: 'Emily Lane',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 3,
      time: '3:00 PM',
    },
    {
      table: 'T-02',
      personAmount: 0,
      personName: '',
      maxPerson: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-03',
      personAmount: 0,
      personName: '',
      maxPerson: 4,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-04',
      personAmount: 0,
      personName: '',
      maxPerson: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-05',
      personAmount: 8,
      personName: 'Brian Richards',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 3,
      time: '9:00 PM',
    },
    {
      table: 'T-06',
      personAmount: 3,
      personName: 'Megan Webb',
      maxPerson: 4,
      status: 'reserved',
      floorNumber: 3,
      time: '9:00 PM',
    },
    {
      table: 'T-07',
      personAmount: 1,
      personName: 'Scott Rodriguez',
      maxPerson: 4,
      status: 'served',
      floorNumber: 3,
      time: '4:30 PM',
    },
    {
      table: 'T-08',
      personAmount: 1,
      personName: 'James Patton',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 3,
      time: '8:30 PM',
    },
    {
      table: 'T-09',
      personAmount: 0,
      personName: '',
      maxPerson: 12,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-10',
      personAmount: 4,
      personName: 'Gloria Wilson',
      maxPerson: 4,
      status: 'served',
      floorNumber: 1,
      time: '12:00 PM',
    },
    {
      table: 'T-11',
      personAmount: 1,
      personName: 'Michael Johnson',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 3,
      time: '9:30 PM',
    },
    {
      table: 'T-12',
      personAmount: 3,
      personName: 'Chad Ayers',
      maxPerson: 4,
      status: 'reserved',
      floorNumber: 1,
      time: '7:30 PM',
    },
    {
      table: 'T-13',
      personAmount: 1,
      personName: 'Nicholas Lowe',
      maxPerson: 12,
      status: 'served',
      floorNumber: 1,
      time: '9:30 PM',
    },
    {
      table: 'T-14',
      personAmount: 2,
      personName: 'Holly Thomas',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 2,
      time: '3:30 PM',
    },
    {
      table: 'T-15',
      personAmount: 0,
      personName: '',
      maxPerson: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-16',
      personAmount: 2,
      personName: 'Justin Barnett',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 1,
      time: '9:30 AM',
    },
    {
      table: 'T-17',
      personAmount: 6,
      personName: 'Kayla Smith',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 1,
      time: '5:00 PM',
    },
    {
      table: 'T-18',
      personAmount: 2,
      personName: 'Tyler Johnson',
      maxPerson: 2,
      status: 'served',
      floorNumber: 1,
      time: '8:30 PM',
    },
    {
      table: 'T-19',
      personAmount: 8,
      personName: 'Tracy Ross',
      maxPerson: 12,
      status: 'served',
      floorNumber: 2,
      time: '11:30 AM',
    },
    {
      table: 'T-20',
      personAmount: 8,
      personName: 'Gary Olson',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 1,
      time: '2:30 PM',
    },
    {
      table: 'T-21',
      personAmount: 0,
      personName: '',
      maxPerson: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-22',
      personAmount: 2,
      personName: 'Rachel Higgins',
      maxPerson: 2,
      status: 'served',
      floorNumber: 3,
      time: '5:00 PM',
    },
    {
      table: 'T-23',
      personAmount: 10,
      personName: 'Sarah Black',
      maxPerson: 12,
      status: 'served',
      floorNumber: 1,
      time: '9:30 AM',
    },
    {
      table: 'T-24',
      personAmount: 8,
      personName: 'Eric Duran',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 2,
      time: '3:30 PM',
    },
    {
      table: 'T-25',
      personAmount: 9,
      personName: 'Sarah Brown',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 3,
      time: '4:30 PM',
    },
    {
      table: 'T-26',
      personAmount: 0,
      personName: '',
      maxPerson: 12,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-27',
      personAmount: 2,
      personName: 'Joseph Perez',
      maxPerson: 2,
      status: 'served',
      floorNumber: 1,
      time: '11:00 AM',
    },
    {
      table: 'T-28',
      personAmount: 0,
      personName: '',
      maxPerson: 2,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-29',
      personAmount: 2,
      personName: 'Darlene Moore',
      maxPerson: 2,
      status: 'served',
      floorNumber: 1,
      time: '5:30 PM',
    },
    {
      table: 'T-30',
      personAmount: 1,
      personName: 'Craig Knight',
      maxPerson: 2,
      status: 'served',
      floorNumber: 1,
      time: '9:30 PM',
    },
    {
      table: 'T-31',
      personAmount: 1,
      personName: 'Gregory Scott',
      maxPerson: 4,
      status: 'reserved',
      floorNumber: 3,
      time: '6:00 PM',
    },
    {
      table: 'T-32',
      personAmount: 2,
      personName: 'Anthony Pierce',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 3,
      time: '10:30 AM',
    },
    {
      table: 'T-33',
      personAmount: 1,
      personName: 'William Anderson',
      maxPerson: 2,
      status: 'reserved',
      floorNumber: 2,
      time: '9:00 PM',
    },
    {
      table: 'T-34',
      personAmount: 0,
      personName: '',
      maxPerson: 2,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-35',
      personAmount: 2,
      personName: 'Emily Johns',
      maxPerson: 4,
      status: 'served',
      floorNumber: 3,
      time: '1:00 PM',
    },
    {
      table: 'T-36',
      personAmount: 0,
      personName: '',
      maxPerson: 4,
      status: 'available',
      floorNumber: 1,
      time: '',
    },
    {
      table: 'T-37',
      personAmount: 4,
      personName: 'Sharon Williams',
      maxPerson: 4,
      status: 'served',
      floorNumber: 1,
      time: '10:30 AM',
    },
    {
      table: 'T-38',
      personAmount: 0,
      personName: '',
      maxPerson: 4,
      status: 'available',
      floorNumber: 3,
      time: '',
    },
    {
      table: 'T-39',
      personAmount: 0,
      personName: '',
      maxPerson: 2,
      status: 'available',
      floorNumber: 2,
      time: '',
    },
    {
      table: 'T-40',
      personAmount: 2,
      personName: 'Lauren Fisher',
      maxPerson: 12,
      status: 'reserved',
      floorNumber: 2,
      time: '3:30 PM',
    },
  ];

  constructor() {}
}
